### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by langston-barrett** [LuxMiranda/herms#67]
The CHANGELOG lists several versions, but there are no [releases on Github](https://help.github.com/articles/about-releases/) nor [tags in Git](https://help.github.com/articles/working-with-tags/). These are good ways to release binaries to users. 

Ultimately, such binaries and source tarballs should be built in Travis. That might be a good feature request to haskell-ci.

**Comment by siddharthist** [comment]
On this subject, `herms` is currently only available via `stack` or `cabal`, but if it had releases it could be added to [nixpkgs](https://github.com/NixOS/nixpkgs) (I could do this).

**Comment by xxxserxxx** [comment]
Binaries would be hugely appreciated. You mention Travis, but would you be willing to use github pipelines? Would it be the shortest path?

**Comment by langston-barrett** [comment]
@xxxserxxx This issue was created before Github Actions existed :smile: I'd be happy to use any solution, and contributions are welcome!

**Comment by xxxserxxx** [comment]
Great! I can submit a pull request that builds herms. It's been over a decade since I used GHC in any real capacity, so I may send it to you short of static compilation, and if you want to cross-compile to other platforms we may need to discuss that due to my limitations, but I can certainly get things rolling.

**Comment by langston-barrett** [comment]
Okay, now that we have a Github Action to build release artifacts, I just need to make and push a tag (and update the changelog, a lot has happened...).

**Comment by langston-barrett** [comment]
Release v2.0(.1) is out! Thanks @xxxserxxx. A good follow-up would be to upload the new version to Hackage.

https://github.com/LuxMiranda/herms/releases/tag/v2.0.1
